# Generated by Django 3.0.5 on 2020-04-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemaster',
            name='site_latitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sitemaster',
            name='site_longitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
