# Generated by Django 3.0.5 on 2020-04-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_companyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='status_stage',
            field=models.SmallIntegerField(default=4),
        ),
    ]
