# Generated by Django 3.0.5 on 2020-04-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200427_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='role',
            field=models.CharField(choices=[('VIEW', 'VIEW'), ('ASSIGN', 'ASSIGN')], max_length=30, null=True, verbose_name='User role in application'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='comp',
            field=models.CharField(choices=[('VYOMA', 'VYOMA'), ('PARK', 'PARK'), ('ATC', 'ATC')], max_length=30, verbose_name='Company Name'),
        ),
    ]
