# Generated by Django 3.0.5 on 2020-04-27 13:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200427_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('compuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CompanyUser')),
            ],
        ),
    ]
