# Generated by Django 3.0.5 on 2020-04-27 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200427_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignuser',
            old_name='compuser',
            new_name='assigned',
        ),
        migrations.AddField(
            model_name='assignuser',
            name='site_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SiteVisit'),
        ),
    ]
