# Generated by Django 3.0.5 on 2020-05-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200501_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcsupplyparameter',
            name='load_current_1_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dcsupplyparameter',
            name='load_current_2_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dcsupplyparameter',
            name='load_current_3_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dcsupplyparameter',
            name='load_current_4_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dcsupplyparameter',
            name='system_voltage_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dcsupplyparameter',
            name='load_current_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcsupplyparameter',
            name='load_current_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcsupplyparameter',
            name='load_current_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcsupplyparameter',
            name='load_current_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcsupplyparameter',
            name='system_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
