# Generated by Django 3.0.5 on 2020-05-05 15:17

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_auto_20200502_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitImagePool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supporting_images', models.ImageField(upload_to=api.models.site_id_directory_path_for_image_pool)),
            ],
        ),
        migrations.AddField(
            model_name='geographicaldetails',
            name='site_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SiteMaster'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='geographicaldetails',
            name='sketch_1',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.site_id_directory_path_for_geographical_details),
        ),
        migrations.AlterField(
            model_name='geographicaldetails',
            name='sketch_2',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.site_id_directory_path_for_geographical_details),
        ),
        migrations.AlterField(
            model_name='geographicaldetails',
            name='sketch_3',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.site_id_directory_path_for_geographical_details),
        ),
        migrations.AlterField(
            model_name='geographicaldetails',
            name='sketch_4',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.site_id_directory_path_for_geographical_details),
        ),
        migrations.DeleteModel(
            name='SupportingImagesGeographical',
        ),
        migrations.AddField(
            model_name='sitevisitimagepool',
            name='sitevisit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SiteVisit'),
        ),
    ]
