# Generated by Django 3.0.5 on 2020-05-05 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_geographicaldetails_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicaldetails',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SiteMaster'),
        ),
    ]
